// Generated by scripts/generate-up-map.cjs. Uses the same projection as the map asset.
export function projectUP(lon, lat) {
 const radians = Math.PI / 180;
 return { x: 225.42191505216135 + (lon * radians - 1.3454276551360058) * 2650.617224257579, y: 395 - (Math.log(Math.tan(Math.PI / 4 + lat * radians / 2)) - 0.42923977282167725) * 2650.617224257579 };
}
export const EDUCATION_MAP_POINTS = {
 school: projectUP(80.9462, 26.8467),
 btech: projectUP(80.9462, 26.8467),
 mtech: projectUP(81.8463, 25.4358),
 phd: projectUP(80.2329, 26.5123),
};
